server:
  port: 8080

spring:
  application:
    name: vortex-gateway

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

    gateway:
      routes:
        - id: user-service
          uri: lb://vortex-user
          predicates:
            - Path=/user/**

        - id: order-service
          uri: lb://vortex-order
          predicates:
            - Path=/order/**
            -
        - id: auth-service
          uri: lb://vortex-auth
          predicates:
            - Path=/auth/**

  redis:
    host: localhost
    port: 6379