<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.vortexlab</groupId>
        <artifactId>vortex-common</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>
    <artifactId>vortex-common-idempotent</artifactId>

    <dependencies>

        <!-- 公共基础模块 -->
        <dependency>
            <groupId>com.vortexlab</groupId>
            <artifactId>vortex-common-core</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>

        <!-- Redis -->
        <dependency>
            <groupId>com.vortexlab</groupId>
            <artifactId>vortex-common-redis</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>

        <!-- Spring AOP -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-aop</artifactId>
        </dependency>

    </dependencies>
</project>
