server:
  port: 9002

spring:
  application:
    name: vortex-auth

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: localhost
    port: 6379

vortex:
  jwt:
    secret:
      vortexlab-secret-key-vortexlab-2026-vortex
    expire:
      604800000
