server:
  port: 9001

spring:
  application:
    name: vortex-user

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  redis:
    host: localhost
    port: 6379

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vortexlab
    username: root
    password: rails@65.40

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true